import React from "react";
import BlogCard from "../components/BlogCard";
import { Divider, Grid, GridItem, Heading } from "@chakra-ui/react";
import { Box } from "@chakra-ui/react";
import Head from "next/head";

const Blogs = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box px={20} py={5}>
        <Heading as="h2" marginTop="5">
          Latest Blogs
        </Heading>
        <Divider marginTop="5" mb={6} />
        <Grid templateColumns="repeat(3, 1fr)" gap={10}>
          {[1, 1, 1].map((e, i) => {
            return (
              <GridItem key={i}>
                <BlogCard />
              </GridItem>
            );
          })}
        </Grid>
      </Box>
    </>
  );
};

export async function getStaticProps() {
  return {
    props: {},
  };
}

export default Blogs;
